### ISSUE TITLE
heroku sever is down

### ISSUE THREAD

**Issue by W-Lawless** [absoftware/abswift-swapi-mvvm#1]
Hello, 

Thank you for this repo! The code is very well structured and easy to follow for even someone new to swift. In cloning and building your project however, it seems the API that this app relied on is down. The app returns the following terminal output on build:

```
📌 RESPONSE

HTTP 404
cf-ray: 5cee5843aa65e3b2-ATL
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Content-Type: text/html; charset=utf-8
cf-request-id: 0508d57e490000e3b2bc932200000001
Cache-Control: no-cache, no-store
cf-cache-status: DYNAMIC
Date: Mon, 07 Sep 2020 06:24:05 GMT
Server: cloudflare
Content-Encoding: br

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<title>No such app</title>
<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
</head>
<body>
<iframe src="//www.herokucdn.com/error-pages/no-such-app.html"></iframe>
</body>
</html>
```

Thanks again, I would love to explore this demo further!

**Comment by absoftware** [comment]
Thank you for your warm feedback 🙂 According to bug it appears that they have changed endpoint URL from `swapi.co` to `swapi.dev`. Or even worse, first one has been closed and second was opened by someone else later. I have fixed this on `master` branch in commit 2872df0110420a6f12291644fbe7d18a03c25778
